
/* Drop Tables */

DROP TABLE ORDERING CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE CUSTOMER
(
	C_ID varchar2(10) NOT NULL,
	C_NAME nvarchar2(10) NOT NULL,
	C_TEL char(13),
	PRIMARY KEY (C_ID)
);


CREATE TABLE ORDERING
(
	O_NO number NOT NULL,
	P_CODE char(4) NOT NULL,
	C_ID varchar2(10) NOT NULL,
	O_PRICE number NOT NULL,
	O_DATE date DEFAULT SYSDATE,
	O_QTY number,
	PRIMARY KEY (O_NO)
);


CREATE TABLE PRODUCT
(
	P_CODE char(4) NOT NULL,
	P_NAME nvarchar2(10) NOT NULL,
	P_PRICE number,
	PRIMARY KEY (P_CODE)
);



/* Create Foreign Keys */

ALTER TABLE ORDERING
	ADD FOREIGN KEY (C_ID)
	REFERENCES CUSTOMER (C_ID)
;


ALTER TABLE ORDERING
	ADD FOREIGN KEY (P_CODE)
	REFERENCES PRODUCT (P_CODE)
;



